.TH "hosp-get" "1" "2018-05-22" "hosp" "ODROID Smart Power Utilities"
.SH "NAME"
.LP
hosp\-get \- get information from an ODROID Smart Power
.SH "SYNPOSIS"
.LP
\fBhosp\-get\fP
.SH "DESCRIPTION"
.LP
Print an ODROID Smart Power's ON/OFF status, START/STOP meter status, and data fields.
.SH "OPTIONS"
.LP
None
.SH "EXAMPLES"
.TP
\fBhosp\-get\fP
Print all status and data values.
.SH "BUGS"
.LP
Report bugs upstream at <https://github.com/energymon/hosp>
.SH "SEE ALSO"
.LP
\fBhosp\-poll\fP(1), \fBhosp\-set\fP(1)